{
 "title": "KCIDB-REST",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kcidb_json_files{job=\"rest_db_kernelci_org\"}",
     "legendFormat": "Submissions"
    }
   ]
  },
  {
   "title": "Submissions rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(kcidb_submissions_total{job=\"rest_db_kernelci_org\"}[$__rate_interval])",
     "legendFormat": "Submissions"
    }
   ]
  },
  {
   "title": "Free inodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "node_filesystem_files_free{job=\"node_db_kernelci_org\", mountpoint=\"/\"}",
     "legendFormat": "inodes"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "kcidb_errors_total{job=\"rest_db_kernelci_org\"}",
     "legendFormat": "Submissions"
    }
   ]
  }
 ]
}