{
 "title": "Linux Exporter Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values({__name__=~\".+\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Core",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate({__name__=\"metrics_requests_denied_total\",instance=~\"${instance}\"}[5m])",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "rate({__name__=\"metrics_requests_total\",instance=~\"${instance}\"}[5m])",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "conntrack",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate({__name__=\"conntrack\",instance=~\"${instance}\"}[5m])",
     "legendFormat": "{{__name__}} {{field}} {{cpu}}"
    }
   ]
  },
  {
   "title": "numa",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "{__name__=\"numa_node_count\",instance=~\"${instance}\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "{__name__=\"numa_node_memory_bytes\",instance=~\"${instance}\"}",
     "legendFormat": "{{__name__}} {{node}} {{type}}"
    },
    {
     "expr": "rate({__name__=\"numa_node_stat_pages\",instance=~\"${instance}\"}[5m])",
     "legendFormat": "{{__name__}} {{node}} {{type}}"
    }
   ]
  },
  {
   "title": "filesystems",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "{__name__=\"filesystem_avail_bytes\",instance=~\"${instance}\"}",
     "legendFormat": "{{__name__}} {{mountpoint}} {{device}} {{fstype}}"
    },
    {
     "expr": "{__name__=\"filesystem_files\",instance=~\"${instance}\"}",
     "legendFormat": "{{__name__}} {{mountpoint}} {{device}} {{fstype}}"
    },
    {
     "expr": "{__name__=\"filesystem_files_free\",instance=~\"${instance}\"}",
     "legendFormat": "{{__name__}} {{mountpoint}} {{device}} {{fstype}}"
    },
    {
     "expr": "{__name__=\"filesystem_files_used\",instance=~\"${instance}\"}",
     "legendFormat": "{{__name__}} {{mountpoint}} {{device}} {{fstype}}"
    },
    {
     "expr": "{__name__=\"filesystem_free_bytes\",instance=~\"${instance}\"}",
     "legendFormat": "{{__name__}} {{mountpoint}} {{device}} {{fstype}}"
    },
    {
     "expr": "{__name__=\"filesystem_size_bytes\",instance=~\"${instance}\"}",
     "legendFormat": "{{__name__}} {{mountpoint}} {{device}} {{fstype}}"
    },
    {
     "expr": "{__name__=\"filesystem_used_bytes\",instance=~\"${instance}\"}",
     "legendFormat": "{{__name__}} {{mountpoint}} {{device}} {{fstype}}"
    }
   ]
  },
  {
   "title": "netdev_sysfs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "{__name__=\"netdev_autoneg\",instance=~\"${instance}\"}",
     "legendFormat": "{{__name__}} {{interface}} {{state}}"
    },
    {
     "expr": "{__name__=\"netdev_carrier\",instance=~\"${instance}\"}",
     "legendFormat": "{{__name__}} {{interface}}"
    },
    {
     "expr": "{__name__=\"netdev_carrier_changes\",instance=~\"${instance}\"}",
     "legendFormat": "{{__name__}} {{interface}}"
    },
    {
     "expr": "{__name__=\"netdev_dormant\",instance=~\"${instance}\"}",
     "legendFormat": "{{__name__}} {{interface}}"
    },
    {
     "expr": "{__name__=\"netdev_duplex\",instance=~\"${instance}\"}",
     "legendFormat": "{{__name__}} {{interface}} {{duplex}}"
    },
    {
     "expr": "{__name__=\"netdev_operstate\",instance=~\"${instance}\"}",
     "legendFormat": "{{__name__}} {{interface}} {{state}}"
    },
    {
     "expr": "{__name__=\"netdev_speed_mbps\",instance=~\"${instance}\"}",
     "legendFormat": "{{__name__}} {{interface}}"
    }
   ]
  },
  {
   "title": "procfs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "{__name__=\"arp_entries\",instance=~\"${instance}\"}",
     "legendFormat": "{{__name__}} {{device}}"
    },
    {
     "expr": "{__name__=\"cpu_boot_time_seconds\",instance=~\"${instance}\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "rate({__name__=\"cpu_context_switches_total\",instance=~\"${instance}\"}[5m])",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "rate({__name__=\"cpu_seconds_total\",instance=~\"${instance}\"}[5m])",
     "legendFormat": "{{__name__}} {{mode}} {{cpu}}"
    },
    {
     "expr": "rate({__name__=\"diskstats\",instance=~\"${instance}\"}[5m])",
     "legendFormat": "{{__name__}} {{device}} {{field}}"
    },
    {
     "expr": "{__name__=\"load_average\",instance=~\"${instance}\"}",
     "legendFormat": "{{__name__}} {{interval}}"
    },
    {
     "expr": "{__name__=\"load_processes\",instance=~\"${instance}\"}",
     "legendFormat": "{{__name__}} {{kind}} {{running}} {{total}} {{latest_pid}}"
    },
    {
     "expr": "{__name__=\"meminfo\",instance=~\"${instance}\"}",
     "legendFormat": "{{__name__}} {field}"
    },
    {
     "expr": "rate({__name__=\"netdev\",instance=~\"${instance}\",field=~\"^(recv_bytes|sent_bytes)$\"}[5m]) * 8",
     "legendFormat": "{{__name__}} {{interface}} {{field}} (bits/s)"
    },
    {
     "expr": "rate({__name__=\"netdev\",instance=~\"${instance}\",field!~\"^(recv_bytes|sent_bytes)$\"}[5m])",
     "legendFormat": "{{__name__}} {{interface}} {{field}}"
    },
    {
     "expr": "rate({__name__=\"netstat\",instance=~\"${instance}\",field=~\"^(ip_ext_in_bcast_octets|ip_ext_in_mcast_octets|ip_ext_in_octets|ip_ext_out_bcast_octets|ip_ext_out_mcast_octets|ip_ext_out_octets)$\"}[5m]) * 8",
     "legendFormat": "{{__name__}} {field} (bits/s)"
    },
    {
     "expr": "rate({__name__=\"netstat\",instance=~\"${instance}\",field!~\"^(ip_ext_in_bcast_octets|ip_ext_in_mcast_octets|ip_ext_in_octets|ip_ext_out_bcast_octets|ip_ext_out_mcast_octets|ip_ext_out_octets)$\"}[5m])",
     "legendFormat": "{{__name__}} {field}"
    },
    {
     "expr": "{__name__=\"processes_blocked\",instance=~\"${instance}\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "rate({__name__=\"processes_forked_total\",instance=~\"${instance}\"}[5m])",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "{__name__=\"processes_running\",instance=~\"${instance}\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "rate({__name__=\"snmp\",instance=~\"${instance}\"}[5m])",
     "legendFormat": "{{__name__}} {field}"
    },
    {
     "expr": "{__name__=\"tcp_sockets\",instance=~\"${instance}\"}",
     "legendFormat": "{{__name__}} {{state}}"
    },
    {
     "expr": "{__name__=\"udp_sockets\",instance=~\"${instance}\"}",
     "legendFormat": "{{__name__}} {{state}}"
    },
    {
     "expr": "{__name__=\"uptime_idle_seconds\",instance=~\"${instance}\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "{__name__=\"uptime_seconds\",instance=~\"${instance}\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "rate({__name__=\"vmstat\",instance=~\"${instance}\"}[5m])",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "softnet",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate({__name__=\"softnet\",instance=~\"${instance}\"}[5m])",
     "legendFormat": "{{__name__}} {{field}} {{cpu}}"
    }
   ]
  }
 ]
}