{
 "title": "New ingester metrics",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Ingestions rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(kcidb_ingestions_total[5m:10s])",
     "legendFormat": "Ingestion rate ({{ingester}})"
    }
   ]
  },
  {
   "title": "Items rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(kcidb_checkouts_total[$__rate_interval])) by (origin)",
     "legendFormat": "Checkouts - {{origin}}"
    },
    {
     "expr": "sum(rate(kcidb_builds_total[$__rate_interval])) by (origin)",
     "legendFormat": "Builds - {{origin}}"
    },
    {
     "expr": "sum(rate(kcidb_tests_total[$__rate_interval])) by (origin)",
     "legendFormat": "Tests - {{origin}}"
    },
    {
     "expr": "sum(rate(kcidb_issues_total[$__rate_interval])) by (origin)",
     "legendFormat": "Issues - {{origin}}"
    },
    {
     "expr": "sum(rate(kcidb_incidents[$__rate_interval])) by (origin)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JSON submission queue size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "kcidb_ingestion_queue", "legendFormat": "Queue size" }
   ]
  }
 ]
}