#!/bin/sh

set -e

repo="${1}"
target="${2}"
git_rev="${3:-staging.kernelci.org}"
user="${4:-admin}"
key="${5:-$PWD/keys/id_rsa_staging.kernelci.org}"

[ "$repo" = "kernelci-backend" ] || [ "$repo" = "kernelci-frontend" ] || {
    echo "Invalid repo name: $repo"
    exit 1
}

[ -z "$target" ] && {
    echo "Missing target"
    exit 1
}

path="checkout/$repo-config"

[ -d "$path" ] || {
    git clone https://github.com/kernelci/"$repo"-config.git "$path"
}

[ -e "$key" ] && key_arg="--private-key $key" || key_arg=""

cd "$path"
git pull --ff-only
ansible-playbook \
    site.yml \
    -i hosts \
    -l "$target" \
    -D \
    -u "$user" \
    -b \
    --skip-tags=secrets \
    -t app \
    $key_arg \
    -e git_head="$git_rev"
cd -

exit 0
