#!/bin/sh

set -e

repo="${1}"
git_rev="${2:-staging.kernelci.org}"
user="${3:-admin}"
target="${4:-staging-api.kernelci.org}"

[ "$repo" = "kernelci-backend" ] || [ "$repo" = "kernelci-frontend" ] || {
    echo "Invalid repo name: $repo"
    exit 1
}

echo "Updating $repo"

path="checkout/$repo-config"
[ -d "$path" ] || {
    git clone https://github.com/kernelci/"$repo"-config.git "$path"
}

key_file="$PWD/keys/id_rsa_staging.kernelci.org"
key_arg=""
[ -e "$key_file" ] && key_arg="--private-key $key_file"

cd "$path"
git pull --ff-only
ansible-playbook \
    site.yml \
    -i hosts \
    -l "$target" \
    -D \
    -u "$user" \
    -b \
    --skip-tags=secrets \
    -t app \
    $key_arg \
    -e git_head="$git_rev"
cd -

exit 0
