- name: Check if first user already exists
  user:
    name: "{{ users[0].username }}"
    state: present
  register: users_exist

- name: Add users for various content upload
  when: users_exist.results | default(false) | bool
  user:
    name: "{{ item.username }}"
    home: "{{ item.home }}"
  with_items: "{{ users }}"

- name: Chown NIPA user home directory
  when: users_exist.results | default(false) | bool
  command: chown -R nipa:nipa /data/storage.kernelci.org/netdev-results

- name: Chown upload user home directory
  when: users_exist.results | default(false) | bool
  command: chown -R upload:upload /data/kernelci.org

- name: Add authorized_keys for users
  when: users_exist.results | default(false) | bool
  authorized_key:
    user: "{{ item.username }}"
    key: "{{ item.key }}"
  with_items: "{{ users }}"

- name: Clone kernelci-deploy repository
  git:
    repo: https://github.com/kernelci/kernelci-deploy.git
    dest: /tmp/kernelci-deploy
    version: main
    force: yes

- name: Copy kernelci-deploy/tools/firmware-updater.py to /usr/local/bin/firmware-updater
  command: cp /tmp/kernelci-deploy/tools/firmware-updater.py /usr/local/bin/firmware-updater.py
  args:
    creates: /usr/local/bin/firmware-updater.py

- name: Make firmware-updater.py executable
  command: chmod +x /usr/local/bin/firmware-updater.py

- name: Run it to self-install
  command: /usr/local/bin/firmware-updater.py

- name: Remove kernelci-deploy repository
  file:
    path: /tmp/kernelci-deploy
    state: absent
