{
 "title": "K8S stats",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(kci_k8s_cluster_status,cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pending tasks (overload)- ALL clusters",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kci_k8s_cluster_status{job=\"k8sexporter\", status=\"pending\", namespace=\"_all_\"}",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "CPU cores available/used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kci_k8s_cluster_status{job=\"k8sexporter\", status=\"total_cpu\", namespace=\"_all_\", cluster=\"$cluster\"}",
     "legendFormat": "Available"
    },
    {
     "expr": "kci_k8s_cluster_status{job=\"k8sexporter\", namespace=\"_all_\", cluster=\"$cluster\", status=\"allocated_cpu\"}",
     "legendFormat": "Allocated"
    },
    {
     "expr": "kci_k8s_cluster_status{job=\"k8sexporter\", namespace=\"_all_\", cluster=\"$cluster\", status=\"used_cpu\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Memory available/used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "kci_k8s_cluster_status{job=\"k8sexporter\", status=\"total_memory\", namespace=\"_all_\", cluster=\"$cluster\"}",
     "legendFormat": "Available"
    },
    {
     "expr": "kci_k8s_cluster_status{job=\"k8sexporter\", namespace=\"_all_\", cluster=\"$cluster\", status=\"allocated_memory\"}",
     "legendFormat": "Allocated"
    },
    {
     "expr": "kci_k8s_cluster_status{job=\"k8sexporter\", namespace=\"_all_\", cluster=\"$cluster\", status=\"used_memory\"}",
     "legendFormat": "Used"
    }
   ]
  }
 ]
}