{
 "title": "Staging",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Staging Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "irate(http_requests_total{job=\"stagingpipemetrics\", kind=\"pipeline_callback\"}[$__interval])",
     "legendFormat": "HTTP Requests rate"
    },
    {
     "expr": "irate(http_requests_total{job=\"stagingapimetrics\"}[$__interval])",
     "legendFormat": "API HTTP Requests"
    }
   ]
  },
  {
   "title": "Staging Load Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "load" } },
   "targets": [
    {
     "expr": "node_load1{job=\"stagingnode\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Staging free mem",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{job=\"stagingnode\", instance=\"staging.kernelci.org:9115\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Staging disk i/o?",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "node_disk_io_now{job=\"stagingnode\", instance=\"staging.kernelci.org:9115\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}