#!/bin/sh -e

REGION=${1}

if [ "${REGION}" = "" ]; then
	echo $0 REGION
	exit 1
fi

if ! type eksctl > /dev/null ; then
	echo eksctl not found
	exit 1
fi

CLUSTER=kernelci-build-${REGION}.${REGION}.eksctl.io

cat build-eksctl.yaml | sed s/REGION/${REGION}/g |
	eksctl create cluster -f -
cat build-resources.yaml | sed s/REGION/${REGION}/g |
	kubectl --cluster ${CLUSTER} apply -f -

../generic/deploy-builder
