- name: Is caddy installed?
  ansible.builtin.stat:
    path: /usr/bin/caddy
  register: caddy_installed

- name: Install caddy
  ansible.builtin.apt:
    name: caddy
    state: present
  when: not caddy_installed.stat.exists

- name: Ensure caddy config directory exists
  ansible.builtin.file:
    path: /etc/caddy
    state: directory
    owner: caddy
    group: caddy
    mode: '0755'

- name: Copy caddyfile
  ansible.builtin.copy:
    src: caddy/Caddyfile
    dest: /etc/caddy/Caddyfile
    owner: caddy
    group: caddy
    mode: '0644'
  tags: caddy

- name: Ensure caddy service is enabled and started
  ansible.builtin.systemd:
    name: caddy
    enabled: true
    state: started

- name: Ensure caddy service is running
  ansible.builtin.systemd:
    name: caddy
    state: restarted
  when: caddy_installed.stat.exists
  tags: caddy

- name: Ensure caddy config is valid
  command: caddy validate --config /etc/caddy/Caddyfile
  register: caddy_validate
  failed_when: caddy_validate.rc != 0
  changed_when: false
  tags: caddy

- name: Ensure caddy is enabled on boot
  ansible.builtin.systemd:
    name: caddy
    enabled: true
  tags: caddy

- name: Restart caddy
  ansible.builtin.systemd:
    name: caddy
    state: restarted
  when: caddy_validate is changed
  tags: caddy
  
- name: Ensure caddy is listening on port 80
  ansible.builtin.wait_for:
    port: 80
    state: started
    delay: 10
    timeout: 30
  tags: caddy

- name: Ensure caddy is listening on port 443
  ansible.builtin.wait_for:
    port: 443
    state: started
    delay: 10
    timeout: 30
  tags: caddy
